/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspaces/ROS/haikalpribadi-ros-pkg/parallax_eddie_robot/srv/Accelerate.srv */
#ifndef PARALLAX_EDDIE_ROBOT_SERVICE_ACCELERATE_H
#define PARALLAX_EDDIE_ROBOT_SERVICE_ACCELERATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace parallax_eddie_robot
{
template <class ContainerAllocator>
struct AccelerateRequest_ {
  typedef AccelerateRequest_<ContainerAllocator> Type;

  AccelerateRequest_()
  : rate(0)
  {
  }

  AccelerateRequest_(const ContainerAllocator& _alloc)
  : rate(0)
  {
  }

  typedef uint16_t _rate_type;
  uint16_t rate;


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/AccelerateRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5d7032a19fb9c1282f0a629414d15b97"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "5d7032a19fb9c1282f0a629414d15b97"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint16 rate\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, rate);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, rate);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(rate);
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AccelerateRequest
typedef  ::parallax_eddie_robot::AccelerateRequest_<std::allocator<void> > AccelerateRequest;

typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateRequest> AccelerateRequestPtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateRequest const> AccelerateRequestConstPtr;


template <class ContainerAllocator>
struct AccelerateResponse_ {
  typedef AccelerateResponse_<ContainerAllocator> Type;

  AccelerateResponse_()
  {
  }

  AccelerateResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/AccelerateResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "5d7032a19fb9c1282f0a629414d15b97"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AccelerateResponse
typedef  ::parallax_eddie_robot::AccelerateResponse_<std::allocator<void> > AccelerateResponse;

typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateResponse> AccelerateResponsePtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::AccelerateResponse const> AccelerateResponseConstPtr;

struct Accelerate
{

typedef AccelerateRequest Request;
typedef AccelerateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Accelerate
} // namespace parallax_eddie_robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5d7032a19fb9c1282f0a629414d15b97";
  }

  static const char* value(const  ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5d7032a19fb9c128ULL;
  static const uint64_t static_value2 = 0x2f0a629414d15b97ULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/AccelerateRequest";
  }

  static const char* value(const  ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint16 rate\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/AccelerateResponse";
  }

  static const char* value(const  ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.rate);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AccelerateRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AccelerateResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<parallax_eddie_robot::Accelerate> {
  static const char* value() 
  {
    return "5d7032a19fb9c1282f0a629414d15b97";
  }

  static const char* value(const parallax_eddie_robot::Accelerate&) { return value(); } 
};

template<>
struct DataType<parallax_eddie_robot::Accelerate> {
  static const char* value() 
  {
    return "parallax_eddie_robot/Accelerate";
  }

  static const char* value(const parallax_eddie_robot::Accelerate&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5d7032a19fb9c1282f0a629414d15b97";
  }

  static const char* value(const parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/Accelerate";
  }

  static const char* value(const parallax_eddie_robot::AccelerateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5d7032a19fb9c1282f0a629414d15b97";
  }

  static const char* value(const parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/Accelerate";
  }

  static const char* value(const parallax_eddie_robot::AccelerateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PARALLAX_EDDIE_ROBOT_SERVICE_ACCELERATE_H

