/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspaces/ROS/haikalpribadi-ros-pkg/parallax_eddie_robot/srv/DriveWithDistance.srv */
#ifndef PARALLAX_EDDIE_ROBOT_SERVICE_DRIVEWITHDISTANCE_H
#define PARALLAX_EDDIE_ROBOT_SERVICE_DRIVEWITHDISTANCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace parallax_eddie_robot
{
template <class ContainerAllocator>
struct DriveWithDistanceRequest_ {
  typedef DriveWithDistanceRequest_<ContainerAllocator> Type;

  DriveWithDistanceRequest_()
  : distance(0)
  , speed(0)
  {
  }

  DriveWithDistanceRequest_(const ContainerAllocator& _alloc)
  : distance(0)
  , speed(0)
  {
  }

  typedef int16_t _distance_type;
  int16_t distance;

  typedef uint16_t _speed_type;
  uint16_t speed;


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/DriveWithDistanceRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8400577676ea99352eba444e9a54a4e6"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "8400577676ea99352eba444e9a54a4e6"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 distance\n\
uint16 speed\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, distance);
    ros::serialization::serialize(stream, speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, distance);
    ros::serialization::deserialize(stream, speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(distance);
    size += ros::serialization::serializationLength(speed);
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DriveWithDistanceRequest
typedef  ::parallax_eddie_robot::DriveWithDistanceRequest_<std::allocator<void> > DriveWithDistanceRequest;

typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceRequest> DriveWithDistanceRequestPtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceRequest const> DriveWithDistanceRequestConstPtr;


template <class ContainerAllocator>
struct DriveWithDistanceResponse_ {
  typedef DriveWithDistanceResponse_<ContainerAllocator> Type;

  DriveWithDistanceResponse_()
  {
  }

  DriveWithDistanceResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/DriveWithDistanceResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "8400577676ea99352eba444e9a54a4e6"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DriveWithDistanceResponse
typedef  ::parallax_eddie_robot::DriveWithDistanceResponse_<std::allocator<void> > DriveWithDistanceResponse;

typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceResponse> DriveWithDistanceResponsePtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::DriveWithDistanceResponse const> DriveWithDistanceResponseConstPtr;

struct DriveWithDistance
{

typedef DriveWithDistanceRequest Request;
typedef DriveWithDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct DriveWithDistance
} // namespace parallax_eddie_robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8400577676ea99352eba444e9a54a4e6";
  }

  static const char* value(const  ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8400577676ea9935ULL;
  static const uint64_t static_value2 = 0x2eba444e9a54a4e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/DriveWithDistanceRequest";
  }

  static const char* value(const  ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 distance\n\
uint16 speed\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/DriveWithDistanceResponse";
  }

  static const char* value(const  ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.distance);
    stream.next(m.speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DriveWithDistanceRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DriveWithDistanceResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<parallax_eddie_robot::DriveWithDistance> {
  static const char* value() 
  {
    return "8400577676ea99352eba444e9a54a4e6";
  }

  static const char* value(const parallax_eddie_robot::DriveWithDistance&) { return value(); } 
};

template<>
struct DataType<parallax_eddie_robot::DriveWithDistance> {
  static const char* value() 
  {
    return "parallax_eddie_robot/DriveWithDistance";
  }

  static const char* value(const parallax_eddie_robot::DriveWithDistance&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8400577676ea99352eba444e9a54a4e6";
  }

  static const char* value(const parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/DriveWithDistance";
  }

  static const char* value(const parallax_eddie_robot::DriveWithDistanceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8400577676ea99352eba444e9a54a4e6";
  }

  static const char* value(const parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/DriveWithDistance";
  }

  static const char* value(const parallax_eddie_robot::DriveWithDistanceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PARALLAX_EDDIE_ROBOT_SERVICE_DRIVEWITHDISTANCE_H

