/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspaces/ROS/haikalpribadi-ros-pkg/parallax_eddie_robot/srv/Rotate.srv */
#ifndef PARALLAX_EDDIE_ROBOT_SERVICE_ROTATE_H
#define PARALLAX_EDDIE_ROBOT_SERVICE_ROTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace parallax_eddie_robot
{
template <class ContainerAllocator>
struct RotateRequest_ {
  typedef RotateRequest_<ContainerAllocator> Type;

  RotateRequest_()
  : angle(0)
  , speed(0)
  {
  }

  RotateRequest_(const ContainerAllocator& _alloc)
  : angle(0)
  , speed(0)
  {
  }

  typedef int16_t _angle_type;
  int16_t angle;

  typedef uint16_t _speed_type;
  uint16_t speed;


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/RotateRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8161fe0896b9846bbd984a50ba5baee3"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "8161fe0896b9846bbd984a50ba5baee3"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 angle\n\
uint16 speed\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, angle);
    ros::serialization::serialize(stream, speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, angle);
    ros::serialization::deserialize(stream, speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(angle);
    size += ros::serialization::serializationLength(speed);
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RotateRequest
typedef  ::parallax_eddie_robot::RotateRequest_<std::allocator<void> > RotateRequest;

typedef boost::shared_ptr< ::parallax_eddie_robot::RotateRequest> RotateRequestPtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::RotateRequest const> RotateRequestConstPtr;


template <class ContainerAllocator>
struct RotateResponse_ {
  typedef RotateResponse_<ContainerAllocator> Type;

  RotateResponse_()
  {
  }

  RotateResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/RotateResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "8161fe0896b9846bbd984a50ba5baee3"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RotateResponse
typedef  ::parallax_eddie_robot::RotateResponse_<std::allocator<void> > RotateResponse;

typedef boost::shared_ptr< ::parallax_eddie_robot::RotateResponse> RotateResponsePtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::RotateResponse const> RotateResponseConstPtr;

struct Rotate
{

typedef RotateRequest Request;
typedef RotateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Rotate
} // namespace parallax_eddie_robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8161fe0896b9846bbd984a50ba5baee3";
  }

  static const char* value(const  ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8161fe0896b9846bULL;
  static const uint64_t static_value2 = 0xbd984a50ba5baee3ULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/RotateRequest";
  }

  static const char* value(const  ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 angle\n\
uint16 speed\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/RotateResponse";
  }

  static const char* value(const  ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::RotateRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.angle);
    stream.next(m.speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RotateRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::RotateResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RotateResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<parallax_eddie_robot::Rotate> {
  static const char* value() 
  {
    return "8161fe0896b9846bbd984a50ba5baee3";
  }

  static const char* value(const parallax_eddie_robot::Rotate&) { return value(); } 
};

template<>
struct DataType<parallax_eddie_robot::Rotate> {
  static const char* value() 
  {
    return "parallax_eddie_robot/Rotate";
  }

  static const char* value(const parallax_eddie_robot::Rotate&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::RotateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8161fe0896b9846bbd984a50ba5baee3";
  }

  static const char* value(const parallax_eddie_robot::RotateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::RotateRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/Rotate";
  }

  static const char* value(const parallax_eddie_robot::RotateRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::RotateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8161fe0896b9846bbd984a50ba5baee3";
  }

  static const char* value(const parallax_eddie_robot::RotateResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::RotateResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/Rotate";
  }

  static const char* value(const parallax_eddie_robot::RotateResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PARALLAX_EDDIE_ROBOT_SERVICE_ROTATE_H

