/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspaces/ROS/parallax_eddie_robot/msg/Ping.msg */
#ifndef PARALLAX_EDDIE_ROBOT_MESSAGE_PING_H
#define PARALLAX_EDDIE_ROBOT_MESSAGE_PING_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace parallax_eddie_robot
{
template <class ContainerAllocator>
struct Ping_ {
  typedef Ping_<ContainerAllocator> Type;

  Ping_()
  : status()
  , value1(0)
  , value2(0)
  {
  }

  Ping_(const ContainerAllocator& _alloc)
  : status(_alloc)
  , value1(0)
  , value2(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  status;

  typedef int16_t _value1_type;
  int16_t value1;

  typedef int16_t _value2_type;
  int16_t value2;


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/Ping"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a9ac828bf931795f5243ecde9378b11f"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string status\n\
int16 value1\n\
int16 value2\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, status);
    ros::serialization::serialize(stream, value1);
    ros::serialization::serialize(stream, value2);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, status);
    ros::serialization::deserialize(stream, value1);
    ros::serialization::deserialize(stream, value2);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(status);
    size += ros::serialization::serializationLength(value1);
    size += ros::serialization::serializationLength(value2);
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::Ping_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::Ping_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Ping
typedef  ::parallax_eddie_robot::Ping_<std::allocator<void> > Ping;

typedef boost::shared_ptr< ::parallax_eddie_robot::Ping> PingPtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::Ping const> PingConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::parallax_eddie_robot::Ping_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::parallax_eddie_robot::Ping_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace parallax_eddie_robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::Ping_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::Ping_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::Ping_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a9ac828bf931795f5243ecde9378b11f";
  }

  static const char* value(const  ::parallax_eddie_robot::Ping_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa9ac828bf931795fULL;
  static const uint64_t static_value2 = 0x5243ecde9378b11fULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::Ping_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/Ping";
  }

  static const char* value(const  ::parallax_eddie_robot::Ping_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::Ping_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string status\n\
int16 value1\n\
int16 value2\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::Ping_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::Ping_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status);
    stream.next(m.value1);
    stream.next(m.value2);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Ping_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parallax_eddie_robot::Ping_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::parallax_eddie_robot::Ping_<ContainerAllocator> & v) 
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "value1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.value1);
    s << indent << "value2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.value2);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PARALLAX_EDDIE_ROBOT_MESSAGE_PING_H

