/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspaces/ROS/parallax_eddie_robot/srv/Travel.srv */
#ifndef PARALLAX_EDDIE_ROBOT_SERVICE_TRAVEL_H
#define PARALLAX_EDDIE_ROBOT_SERVICE_TRAVEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace parallax_eddie_robot
{
template <class ContainerAllocator>
struct TravelRequest_ {
  typedef TravelRequest_<ContainerAllocator> Type;

  TravelRequest_()
  : distance(0)
  , speed(0)
  {
  }

  TravelRequest_(const ContainerAllocator& _alloc)
  : distance(0)
  , speed(0)
  {
  }

  typedef int16_t _distance_type;
  int16_t distance;

  typedef uint16_t _speed_type;
  uint16_t speed;


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/TravelRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8400577676ea99352eba444e9a54a4e6"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "1aac722b8dc69f896e41647fceba2db6"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 distance\n\
uint16 speed\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, distance);
    ros::serialization::serialize(stream, speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, distance);
    ros::serialization::deserialize(stream, speed);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(distance);
    size += ros::serialization::serializationLength(speed);
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TravelRequest
typedef  ::parallax_eddie_robot::TravelRequest_<std::allocator<void> > TravelRequest;

typedef boost::shared_ptr< ::parallax_eddie_robot::TravelRequest> TravelRequestPtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::TravelRequest const> TravelRequestConstPtr;


template <class ContainerAllocator>
struct TravelResponse_ {
  typedef TravelResponse_<ContainerAllocator> Type;

  TravelResponse_()
  : message()
  {
  }

  TravelResponse_(const ContainerAllocator& _alloc)
  : message(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  message;


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/TravelResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5f003d6bcc824cbd51361d66d8e4f76c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "1aac722b8dc69f896e41647fceba2db6"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "string message\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, message);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, message);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(message);
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TravelResponse
typedef  ::parallax_eddie_robot::TravelResponse_<std::allocator<void> > TravelResponse;

typedef boost::shared_ptr< ::parallax_eddie_robot::TravelResponse> TravelResponsePtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::TravelResponse const> TravelResponseConstPtr;

struct Travel
{

typedef TravelRequest Request;
typedef TravelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Travel
} // namespace parallax_eddie_robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8400577676ea99352eba444e9a54a4e6";
  }

  static const char* value(const  ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8400577676ea9935ULL;
  static const uint64_t static_value2 = 0x2eba444e9a54a4e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/TravelRequest";
  }

  static const char* value(const  ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 distance\n\
uint16 speed\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const  ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/TravelResponse";
  }

  static const char* value(const  ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string message\n\
\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::TravelRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.distance);
    stream.next(m.speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TravelRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::TravelResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.message);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TravelResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<parallax_eddie_robot::Travel> {
  static const char* value() 
  {
    return "1aac722b8dc69f896e41647fceba2db6";
  }

  static const char* value(const parallax_eddie_robot::Travel&) { return value(); } 
};

template<>
struct DataType<parallax_eddie_robot::Travel> {
  static const char* value() 
  {
    return "parallax_eddie_robot/Travel";
  }

  static const char* value(const parallax_eddie_robot::Travel&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::TravelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1aac722b8dc69f896e41647fceba2db6";
  }

  static const char* value(const parallax_eddie_robot::TravelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::TravelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/Travel";
  }

  static const char* value(const parallax_eddie_robot::TravelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<parallax_eddie_robot::TravelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1aac722b8dc69f896e41647fceba2db6";
  }

  static const char* value(const parallax_eddie_robot::TravelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<parallax_eddie_robot::TravelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/Travel";
  }

  static const char* value(const parallax_eddie_robot::TravelResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PARALLAX_EDDIE_ROBOT_SERVICE_TRAVEL_H

