/* Auto-generated by genmsg_cpp for file /home/haikalpribadi/Workspaces/ROS/haikalpribadi-ros-pkg/parallax_eddie_robot/msg/KeyStroke.msg */
#ifndef PARALLAX_EDDIE_ROBOT_MESSAGE_KEYSTROKE_H
#define PARALLAX_EDDIE_ROBOT_MESSAGE_KEYSTROKE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace parallax_eddie_robot
{
template <class ContainerAllocator>
struct KeyStroke_ {
  typedef KeyStroke_<ContainerAllocator> Type;

  KeyStroke_()
  : keycode(0)
  {
  }

  KeyStroke_(const ContainerAllocator& _alloc)
  : keycode(0)
  {
  }

  typedef uint8_t _keycode_type;
  uint8_t keycode;


private:
  static const char* __s_getDataType_() { return "parallax_eddie_robot/KeyStroke"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a93d576beb5f3535c249bfdbb8e89901"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "uint8 keycode\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, keycode);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, keycode);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(keycode);
    return size;
  }

  typedef boost::shared_ptr< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct KeyStroke
typedef  ::parallax_eddie_robot::KeyStroke_<std::allocator<void> > KeyStroke;

typedef boost::shared_ptr< ::parallax_eddie_robot::KeyStroke> KeyStrokePtr;
typedef boost::shared_ptr< ::parallax_eddie_robot::KeyStroke const> KeyStrokeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace parallax_eddie_robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a93d576beb5f3535c249bfdbb8e89901";
  }

  static const char* value(const  ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa93d576beb5f3535ULL;
  static const uint64_t static_value2 = 0xc249bfdbb8e89901ULL;
};

template<class ContainerAllocator>
struct DataType< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> > {
  static const char* value() 
  {
    return "parallax_eddie_robot/KeyStroke";
  }

  static const char* value(const  ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 keycode\n\
\n\
";
  }

  static const char* value(const  ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.keycode);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct KeyStroke_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::parallax_eddie_robot::KeyStroke_<ContainerAllocator> & v) 
  {
    s << indent << "keycode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.keycode);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PARALLAX_EDDIE_ROBOT_MESSAGE_KEYSTROKE_H

